In [1]:
import pandas as pd
import seaborn as sd

In [2]:
df= pd.read_csv(r"C:\Users\rehan\Downloads\messy_sales.csv")

In [3]:
df.head(10)

   order_id        date   product  price  qty    zip
0      1254  04/06/2026       mug  11.36    4  60614
1      1057  2026-05-30   charger  14.79    3  30303
2      1150  05/06/2026       mug   5.50    1  10001
3      1066  05/30/2026  notebook    NaN    1  98101
4      1114  04/06/2026    webcam  45.59    4  90405
5      1280  04/22/2026   pen set    NaN    4  30303
6      1204  04/18/2026   charger   8.41    2   2134
7      1249  2026-05-15  keyboard  75.04    4  90405
8      1037  2026-05-19       mug   9.31    2  60614
9      1177  2026-05-13       mug  10.11    3  90210

In [4]:
df.shape

(300, 6)

In [5]:
df.dtypes

order_id      int64
date            str
product         str
price       float64
qty           int64
zip           int64
dtype: object

Three problems
1. The data type of date and zip is wrong
2. Dates aren't properly formatted
3. the zipcode in 6th row is not in the right format

In [6]:
df.isna().sum() #missing values by column

order_id     0
date         0
product      0
price       12
qty          0
zip          0
dtype: int64

In [7]:
fill_value = df["price"].mean() #filling missing values
df["price"] = df["price"].fillna(fill_value)

In [8]:
print(df.duplicated().sum()) #finding and removing duplicates
df = df.drop_duplicates()

8

In [9]:
df["zip"] = df["zip"].astype(str).str.zfill(5)

In [10]:
df["date"] = pd.to_datetime(df["date"], format="mixed")#Standardize the dates

In [11]:
df[df['qty']<0] #investigating wrong values

     order_id       date    product  price  qty    zip
202      1140 2026-04-18     webcam  38.69   -5  98101
262      1233 2026-05-09  desk lamp  22.64   -4  10001
297      1025 2026-04-27   keyboard  47.30   -2  02116

Reason for wrong values
> I'll keep them as they are and when i'm modeling i'll delete them or try to see if there only a -sign and we can just change the sign.

In [12]:
df.to_csv("sales_clean.csv", index=False)

Cleaning Log
1. Used shape to see the dimentions of the table.
2. Used head(10) to view first 10 rows of the table.
3. Used df.duplicated().sum() to get the number of duplicated records.
4. Removed duplicate records with df.dropduplicates(), it removed 8 rows.
5. Changed zip code format and standarized it.
6. Standarized the date by pd.to_datetime(our column, format='mixed')
7. Looked for wrong values in 'qyt, to clean the data later.

>A wrong choice here as have the wrong quatity can show misleading number of sales,
>if we use can lead the business to spend it resources at the wrong place.