In [1]:
import pandas as pd
import seaborn as sd

In [2]:
df=pd.read_csv(r"C:\Users\rehan\Downloads\usarrests.csv")
df.head(10)

    Unnamed: 0  Murder  Assault  UrbanPop
0      Alabama    13.2    236.0        58
1       Alaska    10.0    263.0        48
2      Arizona     8.1    294.0        80
3     Arkansas     8.8    190.0        50
4   California     9.0    276.0        91
5     Colorado     7.9    204.0        78
6  Connecticut     3.3    110.0        77
7     Delaware     5.9    238.0        72
8      Florida    15.4    335.0        80
9      Georgia    17.4      NaN        60

In [3]:
df = df.rename(columns={"Unnamed: 0": "State"})

In [4]:
df.isna().sum()

State       0
Murder      0
Assault     1
UrbanPop    0
dtype: int64

In [5]:
df.describe()

         Murder     Assault   UrbanPop
count  50.00000   49.000000   50.00000
mean    7.78800  182.183673   74.20000
std     4.35551  130.877435   73.40828
min     0.80000   45.000000    6.00000
25%     4.07500  109.000000   53.25000
50%     7.25000  159.000000   66.00000
75%    11.25000  249.000000   77.75000
max    17.40000  879.000000  570.00000

In [6]:
df[df['Assault'].isna()] #Check empty values

     State  Murder  Assault  UrbanPop
9  Georgia    17.4      NaN        60

In [7]:
assault_mean= df['Assault'].mean() #Filling empty values
df['Assault']=df['Assault'].fillna(assault_mean)

1. open the file
2. use describe() to get basic staticts
3. search for empty values
4. filled the empty values( used df['assualt'].fillna(assualt_mean)) #missing value fixed

In [8]:
df[df['UrbanPop']>100] #Checking imposibly high values

   State  Murder  Assault  UrbanPop
14  Iowa     2.2     56.0       570

1. looking for impossible values in UrbanPop Column.
2.  lowa have an impossible high UrbanPop value of 570.
3.   UrbanPop value can't be higher then 100.

In [9]:
df['UrbanPop']=df['UrbanPop'].replace(570,57)

1. i updata the extreme value from 570 to 57,
2. population can't be lower then 0 or highter then 100
3. after analysing other values i concluded 57 is the actual value and the zero at the end is an error.
4. i removed the zero from the end.

In [10]:
df[df['UrbanPop']<10]#For low extreme values

       State  Murder  Assault  UrbanPop
31  New York    11.1    254.0         6

1. Flagging any values that are at the lower extreme. 
2. The value for New York is off from the rest. 
3. It is the smallest value among others in the column.

https://github.com/RehanAhmedSMC/cs82a-data-science-portfolio/tree/main